FROM public.ecr.aws/lambda/nodejs:20 AS build
WORKDIR ${LAMBDA_TASK_ROOT}
COPY package.json package-lock.json ./
RUN npm ci --omit=dev
COPY prisma ./prisma
RUN npx prisma generate
COPY src ./src
CMD ["src/workers/lambdaHandler.handler"]
