server {
    listen 80;
    listen [::]:80;
    server_name __DOMAIN_NAME__;
    server_tokens off;

    access_log /opt/wilmas-fashion/logs/nginx/access.log;
    error_log /opt/wilmas-fashion/logs/nginx/error.log warn;

    root /opt/wilmas-fashion/frontend/dist;
    index index.html;
    client_max_body_size 6m;

    include /etc/nginx/snippets/wilmas-security-headers.conf;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
    }

    include /etc/nginx/snippets/wilmas-app-locations.conf;
}
